name: Send Telegram Alert

on:
  push:
    branches:
      - main

jobs:
  send_alert:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Alert
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Novo commit no branch main! Commit ID: ${{ github.sha }}"
